apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: express-demo-
spec:
  serviceAccountName: build-bot
  params:
    - name: app-name
      value: express-demo-rs
    - name: source-repo
      value: https://github.com/cloud-native-garage-method-cohort/express-demo-rs-ds
    - name: image-repo
      value: quay.io/remiserra/express-demo-rs-ds
  pipelineRef:
    name: express-demo
  workspaces:
    - name: pipeline-shared-data
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 1Gi
          accessModes:
            - ReadWriteOnce