---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - create-configuration.Task.yaml
  - deploy.Task.yaml
  - express-demo-pipeline.yaml
  - git-credentials.secret.yaml
  - production-repository.ConfigMap.yaml
  - quayio-remiserra-macpush.secret.yaml
  - save-configuration.Task.yaml
  - serviceaccount.yaml
  - https://raw.githubusercontent.com/tektoncd/catalog/main/task/npm/0.1/npm.yaml
  - vcs-trigger.yaml
  